<h5>Opret gave</h5>

<div id="present">
  <label>Navn</label><input type="text" name="name"/><br>
  <label>Internt navn</label><input type="text" name="internal_name"/><br>
  <input type="button" onclick="createPresent();" value="Opret" name="Opret"/>
</div>

<script>


function createPresent() {
  submitForm("present","present/Create",onPresentCreated);
}

function onPresentCreated(presentData) {
   alert('Created present with id '+presentData[0].id);
}

</script>


